### ISSUE TITLE
move to github.com/civicrm ?

### ISSUE THREAD

**Issue by JoeMurray** [civicrm/org.civicrm.module.cividiscount#148]
It's kind of hard to find this module right now - could we move it to the main CiviCRM github account?

**Comment by herbdool** [comment]
I second the proposal.

**Comment by thoni56** [comment]
Ditto

**Comment by JoeMurray** [comment]
+1

Joe Murray, PhD
President, JMA Consulting
joe.murray@jmaconsulting.biz
skype JosephPMurray twitter JoeMurray
416.466.1281

**Comment by seanmadsen** [comment]
+1

**Comment by colemanw** [comment]
@dlobo could you please take a minute to migrate this repo. AFAIK, only you have the power to do it :)

**Comment by MegaphoneJon** [comment]
This looks OK to close.
