### ISSUE TITLE
Use of tables causes problems on mobile devices.

### ISSUE THREAD

**Issue by millionleaves** [civicrm/org.civicrm.module.cividiscount#163]
discountButton.tpl outputs the discount form as a table. Getting this to work on a mobile device proved tricky. So, I replaced the tables with divs instead and everything behaved either nicely, or in a way that permitted easy fixing with CSS (actually, for me, it just behaved without additional CSS but my use case is simple).

The code I used is:

```
<div class="form-layout-compressed">
  {foreach from=$discountElements item=discountElement}
    <div class="label nowrap">{$form.$discountElement.label}</div>
    <div>{$form.$discountElement.html}</div>
  {/foreach}
</div>
```

**Comment by adixon** [comment]
Thanks for this, I'd just add a cividiscount class to the surrounding div since that's what the original table has.
