### ISSUE TITLE
Payment Method hidden / unchecked incorrectly

### ISSUE THREAD

**Issue by gareth-circle** [civicrm/org.civicrm.module.cividiscount#164]
main.js file "overwrites" the functionality of Civi JS functions _showHidePayment_ and _skipPaymentMethod_.

I'm not sure they act as intended, or they don't in my scenario which I don't thinks is that unusual.

The cividiscount _skipPaymentMethod()_ function checks to see if the value of a checked priceset is zero, if so, it hides the payment processor / Payment Method section and unchecks the radio option within.

In my situation, I have multiple pricesets so each one does not reflect the actual current total. When I select one of the pricesets that has a zero value the payment method section is hidden and option unset, therefore Civi displays errors saying you need to select a Payment Method, but you can't because it is hidden. If I comment out the entire main.js file everything seems to work as expected.

In the _skipPaymentMethod()_ function within Civi (4.6 anyway), it considers the current total from the 'pricevalue' field, if available, rather than the price set value selected. Is it possible this needs to be worked into your code?

I've also noticed that the main.js file starts with "_if ($('#discountcode').length > 0)_", is that just to see if the discount field is on the page, or if the discount field has something in it? If the latter it doesn't seem correct and maybe requires .val or similar?

**Comment by gareth-circle** [comment]
Just to avoid any confusion, by multiple price sets, I suppose I mean multiple price fields using price sets.

**Comment by mikecalverley** [comment]
This also happens if the applied Discount Code is a 100% discount.

**Comment by pradpnayak** [comment]
Fixed at https://github.com/civicrm/org.civicrm.module.cividiscount/pull/219

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/164
