### ISSUE TITLE
Tracking applied to wrong code if using auto-discount where there's also another valid discount with greater ID

### ISSUE THREAD

**Issue by twomice** [civicrm/org.civicrm.module.cividiscount#167]
Recipe to reproduce:

1. Create an auto-discount for an event, to be automatically applied for current members (other auto-discount configurations may also work to reproduce this), e.g., "MyAutoDiscount"
1. Create another discount code valid for the same event, but not an auto-discount, e.g., "MyWriteInDiscount"; the important thing here is that this step comes after creating the "MyAutoDiscount" code.
1. Visit the CiviDiscount tracking page; observe that the usage tracking for both discounts is at "0".
1. Log in as a contact fitting the auto-discount criteria, and visit the event registration page; leave the "Discount Code" field blank; observe that the discount for "MyAutoDiscount" is properly applied and the registration fee is discounted correctly, and the discount code is correctly described in the fee description.
1. Complete the event registration; again, observe that the discount for "MyAutoDiscount" is properly applied and the registration fee is discounted correctly, and the discount code is correctly described in the fee description.
1. As an administrator, visit the CiviDiscount tracking page; observe that the usage tracking for "MyAutoDiscount" is at 0, and the usage for "MyWriteInDiscount" is at 1.
1. Disable the "MyAutoDiscount" code; create a new code with identical configuration, e.g., "MyAutoDiscount2"
1. Repeat steps 4 and 5, observing the same correct behavior for "MyAutoDiscount2"
1. As an administrator, visit the CiviDiscount tracking page; observe that the usage tracking for "MyAutoDiscount2" is at 1, which is the correct value.

My thoughts so far:
This appears be happening because of some faulty foreach logic in cividiscount_civicrm_buildAmount(). The code at https://github.com/dlobo/org.civicrm.module.cividiscount/blob/master/cividiscount.php#L453 (note the comment, "// this seems to incorrectly set to only the last discount but it seems not to matter in the way it is used") is assigning the last value of the foreach loop in $form->set('_discountInfo'), and that value is used later (around https://github.com/dlobo/org.civicrm.module.cividiscount/blob/master/cividiscount.php#L625) to record the tracking.

That foreach loop is doing a lot, and I haven't had a time to dissect it and be sure any changes don't produce unexpected results.

**Comment by h-c-c** [comment]
If you have only one autodiscount, a workaround is to change it's id to something like 9999.

It works as expected then!  The autodiscount is tracked! 

> That foreach loop is doing a lot, and I haven't had a time to dissect it and be sure any changes don't produce unexpected results.

@twomice You're right. Strangely it's not doing enough either since it just displays the last code twice.    
![workaround](https://cloud.githubusercontent.com/assets/5252344/22356143/28791160-e3fd-11e6-9c0c-dc779c8e0a8e.gif)

**Comment by h-c-c** [comment]
The foreach loop at L363 goes through all discounts, so we have to break out when we hit our autodiscount.   If the last one is our autodiscount then, a broken clock is right twice a day.  ;-)  (see workaround mentioned before.)

Also the discount message stuff at L447 stomps on the $discount object, leaving us withe the wrong $discount['id'].

**Comment by fatcatfablab-admin** [comment]
@twomice Would you mind giving this patch a spin?  Works for me.
