### ISSUE TITLE
Recently upgraded a site to 4.6.25 and Cividiscount is failing

### ISSUE THREAD

**Issue by Upperholme** [civicrm/org.civicrm.module.cividiscount#172]
I look after a site running Drupal 6 (I know - we're working on it), and we recently upgraded to Civi 4.6.26 (we were previously running on 4.5.x). Everything is working fine apart from CiviDiscount. 

When a code is applied, the discounted prices are displayed correctly, but when the user proceeds to complete the transaction, the page comes back with an error saying that the code is invalid. We've tried various permutations of percentage discount vs. fixed amount, ordinary pricing vs. price set, and the result is always the same.

Running on Civi 4.5.x  CiviDiscount 3.2 it was working fine. Both 3.2 and 3.3 are not working. I can see nothing in the CiviCRM log or the PHP error log.

Becuase we're still running with Drupal 6 we are on PHP 5.3.3 - don't know if that's a deal-breaker, but Cividiscount seemed happy enough with it alongside Civi 4.5.x

Any pointers most welcome.

**Comment by eileenmcnaughton** [comment]
Closing this out as 4.6 is kinda gone now
