### ISSUE TITLE
Error appling discount: "Could not find valid value for id"

### ISSUE THREAD

**Issue by diegofcv** [civicrm/org.civicrm.module.cividiscount#176]
Hi,
I'm trying to apply CiviDiscount on an Event. The coupom box is showing and when I insert the discount code and click on Apply button, I get an error page with the information "Could not find valid value for id". I tried twice, both with the same error. It used to work in earlier versions of CiviCRM, in this same environment (now it's Joomla 3.6.5, CiviCRM 4.7.18, PHP 5.5.9). The error stack is:

May 01 21:57:48  [info] $Fatal Error Details = Array
(
    [message] => Não foi possível localizar um valor válido para id
    [code] => 
)

May 01 21:57:48  [info] $backTrace = #0 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Core/Error.php(378): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Utils/Request.php(120): CRM_Core_Error::fatal("Não foi possível localizar um valor válido para id")
#2 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Event/StateMachine/Registration.php(52): CRM_Utils_Request::retrieve("id", "Positive", Object(CRM_Event_Controller_Registration), TRUE)
#3 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Event/Controller/Registration.php(47): CRM_Event_StateMachine_Registration->__construct(Object(CRM_Event_Controller_Registration), TRUE)
#4 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(305): CRM_Event_Controller_Registration->__construct("Registro no Evento", TRUE, "null", NULL, "false")
#5 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#6 /var/www/xxxx/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#7 /var/www/xxxx/components/com_civicrm/civicrm.php(96): CRM_Core_Invoke::invoke((Array:3))
#8 /var/www/xxxx/components/com_civicrm/civicrm.php(11): civicrm_invoke()
#9 /var/www/xxxx/libraries/cms/component/helper.php(405): require_once("/var/www/xxxx/components/com_civicrm/civicrm.php")
#10 /var/www/xxxx/libraries/cms/component/helper.php(380): JComponentHelper::executeComponent("/var/www/xxxx/components/com_civicrm/civicrm.php")
#11 /var/www/xxxx/libraries/cms/application/site.php(191): JComponentHelper::renderComponent("com_civicrm")
#12 /var/www/xxxx/libraries/cms/application/site.php(230): JApplicationSite->dispatch()
#13 /var/www/xxxx/libraries/cms/application/cms.php(261): JApplicationSite->doExecute()
#14 /var/www/xxxx/index.php(49): JApplicationCms->execute()
#15 {main}

Any ideas? Ty.

**Comment by diegofcv** [comment]
Additional info: the problem only happens if more than one event is selected. If I select just one event to be able to use the coupom, is works.

**Comment by mol3earth** [comment]
this happens for us in 4.6.38 and using Stripe. 
this happens for signing up for a single event.
