### ISSUE TITLE
Automatic Discounts Not Working on Events

### ISSUE THREAD

**Issue by themak1985** [civicrm/org.civicrm.module.cividiscount#180]
Using CiviDiscount 3.3, CiviCRM 4.7.1.9 and Wordpress 4.7.5.

When attempting to create an automatic discount for members of type, with status new, current, and grace period or even any current status, I am unable to get a discount to automatically appear on any membership or event pages.  The code I created works, but won't automatically apply for members. This also means anyone with the code, even non-members can use it. What am I doing wrong?

**Comment by herbdool** [comment]
Try different variations, such as leaving out the member type for now. Make sure the user that's making the online purchase has a current membership.

Or could try other fields to see if they'll work.

I was testing it just now and it will apply an auto discount for an event for a user with a current membership.
