### ISSUE TITLE
Cancelling registration with discount does not remove contact from usage count

### ISSUE THREAD

**Issue by kngs** [civicrm/org.civicrm.module.cividiscount#185]
When cancelling an event registration that uses a discount code, shouldn't the usage count for that discount be updated and the contact removed from the usage list?

**Comment by drobinson1356** [comment]
I have the same question

**Comment by colemanw** [comment]
Agreed. To add this feature the extension needs to make use of a hook to respond when participants are updated or deleted. Probably the [postSave hook](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_postSave_table_name/).
