### ISSUE TITLE
Question: discount on overall amount?

### ISSUE THREAD

**Issue by oobi** [civicrm/org.civicrm.module.cividiscount#188]
We want to apply a "scholarship" discount of $500 to an event which has a rather detailed price set. When I select "fixed amount" of $500 it currently subtracts $500 from EACH item in the price set. I know that I can limit which items from the price set it affects.

To clarify - if I have a price set that looks like
ITEM A: $400
ITEM B: $300

A person who selects both those gets invoiced for $700. When the discount is applied I would like $500 subtracted from the total so the invoiced amount is $200. What ACTUALLY happens is that $500 is subtracted from both items so items A and B are now $0. 

We ideally need the price set to be added up as normal and have the discount code take $500 from the total. Is this currently possible - am I missing a config option somewhere?

**Comment by zkrebs** [comment]
I don't think its possible currently. We typically just deduce the $ amount from some price set item and it ends up working out OK. 

A good feature request perhaps!
