### ISSUE TITLE
Bug: Auto discounts not working for membership 

### ISSUE THREAD

**Issue by chamilwijesooriya** [civicrm/org.civicrm.module.cividiscount#194]
Auto discounts feature is not working for memberships.

- CiviDiscount 3.3
- CiviCRM 5.1.1
- Auto populated with default civi data

Steps to reproduce:
1. Create a new discount
2. Add a single membership type 
3. In Automatic Discounts section enter the following:
    Entity : Contact
    API String: {"custom_2":"Single"}
4. Save 
5. Go to a any contact that has Marital Status as Single
6. Goto Memberships -> Add Membership
7. Choose the relevant membership type
8. Verify bug

NB:  custom_2 is Marital Status under Constituent Information

Possible Solution: 
In line 583 of cividiscount.php (cividiscount_civicrm_membershipTypeValue) (v3.3), change:
```
if (!empty($code)) {
    $discounts = $discountCalculator->getDiscounts();
}
```
to:
```
$discounts = $discountCalculator->getDiscounts();
if (empty($code))
    $discounts = $discountCalculator->autoDiscounts;
```

**Comment by MegaphoneJon** [comment]
@chamilwijesooriya Can you submit a pull request?  I'll try to review it when you do.

**Comment by robbrandt** [comment]
This might be the same issue as what I am reporting?  

https://github.com/civicrm/org.civicrm.module.cividiscount/issues/203

But I am using v3.5 and this fix is included.

**Comment by eileenmcnaughton** [comment]
I just tested this on latest Civi (5.8) plus cividiscount from master & it worked fine. I see there has been at least one related fix merged since this was logged so I think it might just be out of date so I'm closing it
