### ISSUE TITLE
Update info file for compatibility with 5.x branches

### ISSUE THREAD

**Issue by arborrow** [civicrm/org.civicrm.module.cividiscount#198]
I am assuming since 4.7 morphed into 5.0 (at least that was my understanding) and that the 5.1-5.3 branches have been updates to that, that this extension is also compatible with 5.0, 5.1, 5.2 and 5.3. Should the info file be updated to reflect that compatibility?

**Comment by colemanw** [comment]
It will work with 5.x even without being marked as such.

**Comment by arborrow** [comment]
Yes, I just wondered if you might want to update the info file to reflect the versions that the extension is compatible with. Peace - Anthony
