### ISSUE TITLE
autodiscount not working if multiple discount instances for same event type

### ISSUE THREAD

**Issue by MtnPavlas** [civicrm/org.civicrm.module.cividiscount#202]
Only the first instance of an auto-discount for a specific event type works while any subsequent instances don't.
E.g. let's assume two discount instances being set up for event type "Class" - one for $20 off, another one for $35 off - each of them has different price options assigned and the same membership requirements to drive the auto-discount, but the $35 auto-discount doesn't work.
Entering the discount code on the event registration page manually works just fine, but the auto-discount doesn't (logged in user is a current member).
No errors in the logs or console.

This worked on CiviDiscount v3.2 and hasn't worked since 3.4 (we skipped 3.3 so can't speak for that version). I just verified 3.2 worked by re-installing it on our website.
Submitting this bug after chatting with Eileen on Town Square.

**Comment by MtnPavlas** [comment]
Hi guys, any other info I can provide? thx

**Comment by colemanw** [comment]
I'm not sure but this might relate to https://github.com/civicrm/org.civicrm.module.cividiscount/pull/181 by @jitendrapurohit

**Comment by midnightspenguin** [comment]
We've run into the same issue. Any idea on what it is going to take to fix it?

**Comment by petednz** [comment]
@jitendrapurohit can you take a look at least in terms of #181

**Comment by MtnPavlas** [comment]
PR #210 totally fixes this issue; chance this can get committed vs. us having to patch it after every CiviDiscount upgrade? Thank you!

**Comment by petednz** [comment]
also this one @seamuslee001 ?

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/202
