### ISSUE TITLE
Autodiscount filtering on custom fields

### ISSUE THREAD

**Issue by robbrandt** [civicrm/org.civicrm.module.cividiscount#203]
I am trying to use the autodiscount function, filtering on a custom field.  Using

CiviCRM 5.4.1
CiviDiscount 3.5

The custom field has been added to the civicrm_value_demographics table, and the field is award_fee_opt_out_405 (a checkbox that sets value as 1)

I have my discount set as:
$30 discount
Automatic discount for existing members of type: "Student"
Automatic discount for Membership Statuses - "--any current status--"
Specify entity for advanced autodiscount: "contact" (have also tried "value_demographics" and "civicrm_value_demographics")
Specify api string for advanced filter: {"custom_405":"1"}

What am I missing?

**Comment by chamilwijesooriya** [comment]
Did you select which membership types the discount should be applied to?

**Comment by robbrandt** [comment]
Yes, I've tried with and without the "Student" membership being selected in "Discounts for memberships" and in "Automatic discount for existing members of type".

**Comment by robbrandt** [comment]
I found the issue.  We have a complicated contribution form, and another extension manages that complexity in a way that CiviDiscount doesn't anticipate.  Rather, the extension should anticipate that CiviDiscount needs some extra help.  We'll address it from that perspective.

**Comment by chamilwijesooriya** [comment]
alright cool. If in doubt, always try to check if the issue persists in the demo website (https://dmaster.demo.civicrm.org/)

**Comment by robbrandt** [comment]
On further consideration, it may not purely be an issue with our other extension.

Suppose the field you are keying an autodiscount for is something the contact is filling out himself on the contribution page. For example, in your #194 issue you use custom_2/Single.  If the contact checks that "Single" box on the contribution form itself, will the price be updated?  It seems not.  Some ajax would be necessary to do that, correct?

**Comment by chamilwijesooriya** [comment]
It's not possible because discounts are calculated against saved database values. Since the user hasn't submitted/saved the form yet, it won't calculate the discounts considering that field. Even if you used AJAX, autodiscounts won't be applied. You can see the code here [CRM_CiviDiscount_DiscountCalculator::checkDiscountsByEntity() ](https://github.com/civicrm/org.civicrm.module.cividiscount/blob/master/CRM/CiviDiscount/DiscountCalculator.php#L190)
You can however use AJAX and implement your own discount calculating method. And you can make use of methods provided in CiviDiscount

**Comment by eileenmcnaughton** [comment]
@robbrandt I'm going to close this - I think there wasn't any intention when custom field filtering was added that it would respond in real time & I have reservations about whether adding that would risk adding unpredictability. Regardless there doesn't seem to be an open problem here
