### ISSUE TITLE
Unable to edit participant records with 100% or $0 registration

### ISSUE THREAD

**Issue by tommybobo** [civicrm/org.civicrm.module.cividiscount#216]
Similar to #186 but not related to usage numbers.

A contact uses a 100% discount code. If the participant record is edited, the discount code does not load automatically thus resetting the price of the registration to the default price. If saved it totally overwrites the discount and appears that the contact owes money for the event.

If a $0 contribution is created along with the registration, this issue does not occur.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/216
