### ISSUE TITLE
Unable to complete event registration with 100% discount coupon and PayPal Express

### ISSUE THREAD

**Issue by alexmarketaccess** [civicrm/org.civicrm.module.cividiscount#217]
Using Joomla 3.9.3 and civiCRM 5.10.4

I have a discount code that offers a 100% discount on an event. 

I use PayPal Express as the payment method for the event.

I've discovered a problem though: with the 100% discount, the PayPal button disappears (which makes total sense), but then there is no way to complete the registration process.

I've created a short screen movie to demonstrate the issue:

https://drive.google.com/file/d/1-LQX2ceRQpqZqQCrwXi7IuSOgFDsC8UV/view?usp=drivesdk

I cannot change the payment method -- an hope of a fix for this situation (or perhaps a workaround)?

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/217
