### ISSUE TITLE
Discount code invalid for price set item

### ISSUE THREAD

**Issue by robbrandt** [civicrm/org.civicrm.module.cividiscount#218]
We use discount codes a lot. I would like to think I know what I'm doing :)

But for the first time we are trying to create a discount code for a price set item - as opposed to a membership type.

This is an item where the visitor specifies a quantity of an item costing $10.  We want to get them a $10 discount (i.e., one item free). So the field in question is of type "Text / Numeric Quantity".

The discount code itself is configured as active, fixed amount $10, usage limit 1, and the Price Field option has the Text / Numeric Quantity field in question selected.

Have I missed something?

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/218
