### ISSUE TITLE
auto discount for volunteers

### ISSUE THREAD

**Issue by netzih** [civicrm/org.civicrm.module.cividiscount#220]
Not sure if there is such an option and I just do not know how to add it it.
but it would be nice to add an option to apply automatic discount for those who signup as volunteer for events

Thank you

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/220
