### ISSUE TITLE
CiviDiscount does not affect line item amounts

### ISSUE THREAD

**Issue by agileware-fj** [civicrm/org.civicrm.module.cividiscount#224]
CiviDiscount does not affect line item amounts

Steps to reproduce:

1. Set up a discount code to work with memberships
2. Start an offline membership renewal
3. Enter the discount code on the renewal form
4. observe the amounts have been changed on the form
5. submit the renewal
6. observe the total amount of the resulting contribution is correct
7. print an invoice for the contribution, or use some other method to check the line item amounts

Expected results:

- The line item amount is adjusted for the discount
- The total amount corresponds to the sum of the line items

Actual results:

- The line item amount does not have the discount applied
- There is no additional line item for the discount
- The total amount has the discount applied, so is less than the sum of the lines.

I suspect this may be the results of hook_civicrm_buildAmount not actually being conferred to line items.

**Comment by agileware-fj** [comment]
Agileware ref CIVICRM-1286

**Comment by agileware-fj** [comment]
This may actually be a core issue, but seeing as cividiscount is the affected workflow, this seemed like a better place to start from.

**Comment by davejenx** [comment]
@agileware-fj I filed this core issue a few months ago: [Incorrect line item created for back-end membership sign-up using price set and CiviDiscount](https://lab.civicrm.org/dev/core/issues/860). Do the conditions and symptoms fit? I was only able to replicate it in the specific conditions described there:

> When doing a back-end membership sign-up using a price set, with an additional item e.g. donation and with a CiviDiscount code applying to the membership, the line item created for the membership does not reflect the discount but the contribution total does. The problem does not occur without the additional item.

I spent some time looking at it in a debugger and found that the price set was being instantiated twice, once with the discount, once without, causing the line items to be calculated without the discount. However if there was only one item, a different route through the code kicked in, overriding the line item amount.

I came up with a couple of approaches to fixing but they need more testing and review. I'm aiming to work on this a bit today/tomorrow, I'll update here with any progress & a link to a PR if I get that far.

Cheers,

Dave

**Comment by davejenx** [comment]
@agileware-fj Core PR created: https://github.com/civicrm/civicrm-core/pull/14994 - would be great if you could test & review.

**Comment by davejenx** [comment]
@agileware-fj That PR had test failures, I'm going for an alternative approach: https://github.com/civicrm/civicrm-core/pull/15004 - again would be great if you could test & review.

**Comment by JoeMurray** [comment]
@monish please monitor this thread and help push to complete and merge in coming days.

**Comment by agileware-fj** [comment]
@davejenx sounds about right, except we didn't need to add an additional amount.  Sound like this is most likely a core issue based on that, although seems like there are some opinions on your second PR's approach already.

**Comment by agileware-fj** [comment]
After fix to dev/core#860 and some more extensive testing, I've determined that this is not a cividiscount issue.  Closing.
