### ISSUE TITLE
Additional participants only applies to last person

### ISSUE THREAD

**Issue by martinh-pw** [civicrm/org.civicrm.module.cividiscount#225]
So I've changed the __cividiscount_allow_multiple_ value as per issue #88, so that when multiple people register only the first one (the member themselves) gets the member discount and their friends don't.

However this doesn't apply properly.
- Change the return value of the _cividiscount_allow_multiple() function to be FALSE.
- Start an event registration for a logged in user who has a membership, which triggers a discount that has an "automatic discount" set up.
- Select to register multiple participants (3 or more), on the first page.
- Fill in these registrations on the multiple pages. On the first page the discounted price will be provided (correct), and on the following pages the non-discounted regular price will be provided (correct).
- When arriving on the final confirmation page before completing the registration, look at the prices. Note that ALL the registrations except the very last one have the discounted price (incorrect).

**Comment by martinh-pw** [comment]
Ok so after some experimenting, it seems like testing for this case at cividiscount.php:330 (roughly) fixes this. I'm not sure if something has changed in Civi's form processing to require this? Also not sure if the other conditions in this block can now be removed?

Condition to test:
if (get_class($form) == 'CRM_Event_Form_Registration_AdditionalParticipant')

**Comment by ginkgomzd** [comment]
Thanks for this @martinh-pw .

I had a little bit of a hard time understanding your solution. I wasn't clear that the condition was to return when true.

here is how we hacked it:

```diff
commit ce30f97f2c602d395a67fae9a8dc95c085020985
Author: ginkgoMZD <mzd@ginkgostreet.com>
Date:   Thu Aug 29 14:57:32 2019 -0400

    SUP-1917 disable discounts for additional party sea-pants;

diff --git a/cividiscount.php b/cividiscount.php
index 6816316..22cffba 100644
--- a/cividiscount.php
+++ b/cividiscount.php
@@ -326,6 +326,10 @@ function cividiscount_civicrm_buildAmount($pageType, &$form, &$amounts) {
       }
     }
 
+    if (get_class($form) == 'CRM_Event_Form_Registration_AdditionalParticipant') {
+      return;
+    }
+
     $form->set('_discountInfo', NULL);
     $discountEntity = ($pageType == 'membership') ? 'membership_type' : 'event';
     $discountCalculator = new CRM_CiviDiscount_DiscountCalculator($discountEntity, $eid, $contact_id, $code, FALSE);
@@ -929,7 +933,7 @@ function _cividiscount_ignore_case() {
  * TODO: Add settings for admin to set this.
  */
 function _cividiscount_allow_multiple() {
-  return TRUE;
+  return FALSE;
 }
 
 function _cividiscount_get_tracking_count($cid) {

```

**Comment by martinh-pw** [comment]
Yes that's the idea, however a minor difference in the first change. I've made this change one line earlier in code, to keep it within the loop for "if (!_cividiscount_allow_multiple())". 

```
***************
*** 326,331 ****
--- 326,335 ----
            }
          }
        }
+       // Bug fix: https://github.com/civicrm/org.civicrm.module.cividiscount/issues/225
+       if (get_class($form) == 'CRM_Event_Form_Registration_AdditionalParticipant') {
+         return;
+       }
      }

      $form->set('_discountInfo', NULL);
***************
*** 939,944 ****
--- 943,950 ----
   * TODO: Add settings for admin to set this.
   */
  function _cividiscount_allow_multiple() {
+   // https://github.com/civicrm/org.civicrm.module.cividiscount/issues/88
+   return FALSE;
    return TRUE;
  }
```

**Comment by ginkgomzd** [comment]
ah, good point!

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/225
