### ISSUE TITLE
Search interface?

### ISSUE THREAD

**Issue by robbrandt** [civicrm/org.civicrm.module.cividiscount#226]
We frequently use discount codes to grant memberships to specific people.  Our membership director has asked me to to help her create a followup process in which she can find unused discount codes that are (say) 2, 4, or 8 weeks old.  But I can't find a where I can do a search that will find anything about discount codes, or for example create a smart group.

Suggestions?

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/226
