### ISSUE TITLE
CiviDiscount overrides the amount regardless the number of terms for membership

### ISSUE THREAD

**Issue by agileware-fj** [civicrm/org.civicrm.module.cividiscount#228]
Cross-posting from [extensions/cividiscount#3](https://lab.civicrm.org/extensions/cividiscount/issues/3) since no response there

The amount is overridden regardless of the terms. But the expired date is right.

Not sure that this isn't an artefact of the core Membership form; see also [dev/core#1250](https://lab.civicrm.org/dev/core/issues/1250)

# Step to reproduce:
1. create a discount code for membership
2. create or renew membership with credit card
3. set the terms to two or more
4. submit and check the created contribution and membership

For example, the membership fee is $100 per term. We submit the form with 3 terms. The discount is 25% off.

# Expected results:
1. contribution amount is adjusted correctly: 100 * 3 * 75% = 225
2. membership expired date matches the terms: 3 terms

# Actual results:
1. contribution amount is one term price adjusted by the discount: 75
2. membership expired date matches the terms: 3 terms

# Comments:
It **looks** like this could be due to the total amount override in the `hook_civicrm_membershipTypeValues()` implementation, which also potentially disregards any changes to the amount given on the form; see [civicdiscount.php#L592](https://github.com/civicrm/org.civicrm.module.cividiscount/blob/0ec0f64/cividiscount.php#L592)

Agileware ref: CIVICRM-1307

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/228
