### ISSUE TITLE
Feature : Control whether each discount coupon applies to new memberships, membership renewals

### ISSUE THREAD

**Issue by sunilpawar** [civicrm/org.civicrm.module.cividiscount#230]
Example:
Contact A having Student Membership, There is discount code available for student membership but we can not set rule that: this code is only available for New Applicant and Existing Member can not use it. Other way around is : discount only available for Existing Member and not available for New Member.

Here is [PR ](https://github.com/civicrm/org.civicrm.module.cividiscount/pull/231)

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/230
