### ISSUE TITLE
100% discount with Stripe processor leads to data not making it to confirmation

### ISSUE THREAD

**Issue by twjordan** [civicrm/org.civicrm.module.cividiscount#236]
I have posted this issue in the Stripe processor plugin gitlab too because I can’t tell where the issue is. https://lab.civicrm.org/extensions/stripe/-/issues/190

I have a WP + CiviCRM setup using CiviContribute to sign up members taking payment with Stripe. I have a 100% discount code for members with financial hardships.
I recently discovered that when a potential member uses the 100% discount and tries to continue with registration, the confirmation page doesn’t contain any of their information other than email address and they cannot register. The data missing even includes the membership type.
Our form has an additional contribution option and I found that I could put $1 into that field and a valid credit card in, go to confirmation and see my data there, then “GO BACK” to the form, clear out the $1 and I would be able to finish registration with no fee.
This leads me to suspect that there is some sort of handoff that doesn’t occur when the Stripe CC entry and billing address information are not present on the form.
Any assistance would be welcome.  The form is at https://parkingreform.org/join/

**Comment by mattwire** [comment]
Fixed in Stripe 6.6
