### ISSUE TITLE
Usage tracking issue for memberships

### ISSUE THREAD

**Issue by gibsonoliver** [civicrm/org.civicrm.module.cividiscount#237]
Hi 

We have a client who has noticed an issue with the way the usage of codes is tracked.
Using CiviCRM 5.24.6 and CiviDiscount 3.8.1. 

I've just done some tests and;

Membership - external people use a code. The code applies fine and has its usage tracked.
Membership - staff use a code via the CRM interface. The discount is applied. But it doesn't record that this code has been used (usage tracked count).

I've compared this against event code tracking.
When staff use an event discount code, via the CRM interface, this usage is tracked. 

Oliver

**Comment by eileenmcnaughton** [comment]
This change seems to be the cause https://github.com/civicrm/org.civicrm.module.cividiscount/commit/ea623304f00e48ef3bdceb3fdb7c5cacc1c4b4a2 but there is not enough info about the problem it was solving to see what happens when it's removed

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/237
