### ISSUE TITLE
fix Js error when none option present in price field

### ISSUE THREAD

**Issue by sunilpawar** [civicrm/org.civicrm.module.cividiscount#239]
When you create Multiple price field in one price set, and one of the price field is not required, then civicrm give additional option to say `- none -`, this element does not contain `data-amount` attribute. This lead to generate JS Error.

This fix, will check `data-amount` attribute exist. if not, it return for continue next iteration.

<img width="883" alt="Screenshot 2020-08-30 at 7 15 07 PM" src="https://user-images.githubusercontent.com/377735/91660832-bdc65400-eaf5-11ea-933d-c0b700cf3368.png">

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/239
