### ISSUE TITLE
Blank description prints '_null' instead of nothing

### ISSUE THREAD

**Issue by freeform-sg** [civicrm/org.civicrm.module.cividiscount#248]
When the membership discount code text is being appended to the affected price option label, the text " null" is being added after the savings value, it appears to be the result of leaving the discount code's description blank. We're using "&nbsp;" as a description as a workaround.
![screenshot-dev ssc ca-2021 01 20-00_13_04](https://user-images.githubusercontent.com/2062046/105130756-99bfdb00-5ab5-11eb-9644-01cd29e885e9.png)

**Comment by amruta-kashikar** [comment]
I want to work on this issue

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/248
