### ISSUE TITLE
Register another participant discount applied to duplicate contact

### ISSUE THREAD

**Issue by cjweddell** [civicrm/org.civicrm.module.cividiscount#249]
A member (benefiting from a members discount of 100% to an event) registered a friend who was not a member having clicked on register another participant.
![image](https://user-images.githubusercontent.com/68421405/105518035-ad468e00-5ccf-11eb-8d0c-a6b3cfec7e79.png)

While I can understand (but wish it didn't happen this way) that because they were still logged in their friend also got the discount.  However I also noticed it created 2 contact records for the friend...

1. (the first according to the timestamp) that included:
- The activity 'Event Registration' by person for (with) the friend
- The redeemed code
- it also added the friend to the group set up for anyone using the event registration

2. (the second according to the timestamp) that included:
- The contribution for the event fee
- Recorded as a Status=Registered, Role=Attendee for the Event
- Activities were recorded for scheduled reminders associated with the event
- it also added the friend to the group set up for anyone using the event registration

The user experience for the person making the booking when they submitted the booking was 'a blank screen'.

Production environment:
- WordPress 5.6
- CiviCRM 5.32.1
- CiviDiscount 3.8.2

I get a similar experience on my test system.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/249
