### ISSUE TITLE
When two or more discounts apply to the same thing, what is the queue of priority?

### ISSUE THREAD

**Issue by Stoob** [civicrm/org.civicrm.module.cividiscount#258]
I'm trying to figure out how automatic discounts are applied, and what the queue is based on.

First I made a $30 discount and then a $40 one, both automatically applied based on membership to the same event.  The $30 discount was the one that was applied automatically.  When I disabled the $30, then re-enabled it, then the $40 discount was applied automatically from there on out.  What is the intended behavior?  

Thoughts @coleman or anyone?

**Comment by colemanw** [comment]
Hey @Stoob - blast from the past (both commenting on an old issue, and hey long time no see!)

It sounds to me like it's just applying the first one it finds. You can probably confirm that by creating 2 new discounts and this time create the $40 one before you create the $30. I'll bet the $40 one will be applied.

**Comment by Stoob** [comment]
That is correct @colemanw with an interesting twist.  Disabling a discount does two things:
1. moves the disabled discount to the back of the application queue, even once it is re-enabed
2. removes all conditions from the discount (erases Event Type, Automatic, etc)
Is either a cause for concern?

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/258
