### ISSUE TITLE
Discount for any event does not work

### ISSUE THREAD

**Issue by AlainBenbassat** [civicrm/org.civicrm.module.cividiscount#262]
- create a discount code called "free" (name doesn't matter)
- fill in a discount amount of 100 percent
- in the section "Discounts for events", select Events: "-- any event ---"

Then register a participant and try to apply that code.
You will get the error: The discount code you entered is invalid.

Noticed in CiviCRM v5.36.1 and CiviDiscount 3.8.3, but you can simulate it in the current demo environment (dmaster.demo.civicrm.org - 5.38.alpha1)

Edit: I did some more tests:
- CiviCRM 5.36.1 + CiviDiscount 3.8.1 + above discount code ==> works fine
- CiviCRM 5.36.1 + CiviDiscount 3.8.2 + above discount code  ==> Error

**Comment by agileware-justin** [comment]
Just confirming this is still a problem with CiviDiscount 3.8.3 and CiviCRM 5.37.2

**Comment by agileware-justin** [comment]
Just noting that the workaround is to select all the available Event Types, then the discount is available for all events and it can be applied.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/262
