### ISSUE TITLE
Automatic discounts not being applied after server updates

### ISSUE THREAD

**Issue by lkuttner** [civicrm/org.civicrm.module.cividiscount#266]
Following updates to PHP 7.3.29 and MySQL 5.7.34 earlier this month, we discovered that discounts are no longer being automatically applied to event registration forms, public or back-end.  The discount codes do work when applied manually.  No errors are being logged.  We just updated CiviDiscount to 3.8.2 from an older version, but that did not resolve the problem.  We are on CiviCRM 5.33.5 on Drupal 7.8.1.  Any ideas what might be causing this?  Thanks very much.

**Comment by lkuttner** [comment]
This appears of be a version compatibility issue, as price sets that were created before 2019 still display properly.  If I copy or try to update an old price set, they stop displaying the discounts.

**Comment by lkuttner** [comment]
I have submitted this as a possible issue with price sets:  [https://lab.civicrm.org/dev/core/-/issues/2727](https://lab.civicrm.org/dev/core/-/issues/2727)

**Comment by lkuttner** [comment]
I was able to remedy this by applying this submitted commit in cividiscount.php from 2018 that was never implemented, and so far it seems to be good.
```
-  if ($autodiscount) {                           
+  if ($autodiscount && $discountApplied) { 
```
Previous issue: https://github.com/civicrm/org.civicrm.module.cividiscount/pull/210/commits/1c5ba03a973f4799d62108e6d8e62d2348368a8c

I do not know why the past three years of price sets that had been displaying properly stopped doing so after the PHP and MySQL updates, but this code change has resolved it.

**Comment by lkuttner** [comment]
Apparently, while the change resolves the missing discount for a price set with a single discount code, it does not fix it for price sets with multiple discounts applied.  Only the first discount is being applied.  Further changes are needed.

**Comment by lkuttner** [comment]
I am now seeing some additional strange behavior on our dev server with CiviDiscount 3.8.4.  If I go to edit existing discounts from the last few years, the previously selected events in the Discounts for Events  field are no no longer displayed and  events in the last few years no longer appear in the pick list and there are some blank lines instead.  Price field options are also gone.  I rebooted the server just in case something was hung, and there is no change.

**Comment by lkuttner** [comment]
Latest work-around that seems to function properly on CiviDiscount 3.7 on our production server:
```
- if ($autodiscount) {
-        break;
+ if (!$autodiscount) {
+        continue;
```
We are still experiencing the puzzling issues mentioned above on our dev server with CiviDiscount 3.8.4.
Hopefully someone familiar with the code will be able to work through this and determine what the issue is.

**Comment by mercurymotos** [comment]
Thanks to lkuttner for identifying this issue and providing a functional - if temporary! - fix.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/266
