### ISSUE TITLE
Add support for a private description/source field and tags for a DiscountCode

### ISSUE THREAD

**Issue by ananelson** [civicrm/org.civicrm.module.cividiscount#268]
We just imported thousands of legacy discount codes from an old system. The "description" field is displayed to the public so it is not a good place to put internal metadata.

It would be helpful to have an internal/private:
- narrative descriptive field 
- tag system for organizing/searching codes

I may be able to write a patch for this in a few months.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/268
