### ISSUE TITLE
adjust usage count when transaction cancelled

### ISSUE THREAD

**Issue by ananelson** [civicrm/org.civicrm.module.cividiscount#271]
If you have limited the number of times a given discount code can be used, cancelling a contribution should restore 1 usage to the discount code.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/271
