### ISSUE TITLE
Time for a new maintainer of this extension?

### ISSUE THREAD

**Issue by agileware-justin** [civicrm/org.civicrm.module.cividiscount#273]
Time for a new maintainer of this extension?

**Comment by colemanw** [comment]
AFAIK there is no maintainer. Any volunteers would be very welcome.

**Comment by mattwire** [comment]
I would suggest we move it to lab.civicrm.org and at the same time assign new maintainer(s)

**Comment by agileware-justin** [comment]
If this extension is moved to Gitlab, it would really be ideal if the Github issues and open PRs could be moved there too. If not then I'd say just keep it here.

**Comment by agileware-justin** [comment]
So how do we Make It Happen?

**Comment by mlutfy** [comment]
Moved: https://lab.civicrm.org/extensions/cividiscount/-/issues/273
